#include "meta.h"

#include <stdio.h>
#include <string.h>

/*
 * Decodes an opcode into a string including the opcodes
 * arguments. Adapted from EMUTools.
 */
void meta_parse(char* meta, size_t len, const uint8_t* p)
{
    char *d, *t;
    char  b[20];

    if (*p == 0xCB) { p++; d = ext_opcode_meta[*p++].description; }
    else { d = opcode_meta[*p++].description; }

    if (d == NULL)
    {
            snprintf(meta, len, "INVLD 0x%02X", *(p - 1));
    }
    else if ((t = strchr(d, '*')) != NULL)
    {
        strncpy(meta, d, t - d);
        meta[t - d] = '\0';

        snprintf(b, sizeof b, "%02X", *p++);
        strncat(meta, b, len - 1);
        strncat(meta, t + 1, len - 1);
    }
    else if ((t = strchr(d, '@')) != NULL)
    {
        strncpy(meta, d, t - d);
        meta[t - d] = '\0';

        strncat(meta, *p & 0x80 ? "-" : "+", len - 1);
        snprintf(b, sizeof b, "%02X", *p & 0x80 ? 256 - *p : *p);
        strncat(meta, b, len - 1);
        strncat(meta, t + 1, len - 1);
    }
    else if ((t = strchr(d, '#')) != NULL)
    {
        strncpy(meta, d, t - d);
        meta[t - d] = '\0';

        snprintf(b, sizeof b, "%04X", p[1]*256 + p[0]);
        strncat(meta, b, len - 1);
        strncat(meta, t + 1, len - 1);
    }
    else
    {
        strncpy(meta, d, len);
    }
}

#define OPCODE(x, y) {x, y}

opcode_meta_t const opcode_meta[] = {
	/* 0x00 */ OPCODE(               "NOP",  4),
	/* 0x01 */ OPCODE(          "LD BC,#h", 12),
	/* 0x02 */ OPCODE(         "LD (BC),A",  8),
	/* 0x03 */ OPCODE(            "INC BC",  8),
	/* 0x04 */ OPCODE(             "INC B",  4),
	/* 0x05 */ OPCODE(             "DEC B",  4),
	/* 0x06 */ OPCODE(           "LD B,*h",  8),
	/* 0x07 */ OPCODE(              "RLCA",  4),
	/* 0x08 */ OPCODE(        "LD (#h),SP", 20),
	/* 0x09 */ OPCODE(         "ADD HL,BC",  8),
	/* 0x0A */ OPCODE(         "LD A,(BC)",  8),
	/* 0x0B */ OPCODE(            "DEC BC",  8),
	/* 0x0C */ OPCODE(             "INC C",  4),
	/* 0x0D */ OPCODE(             "DEC C",  4),
	/* 0x0E */ OPCODE(           "LD C,*h",  8),
	/* 0x0F */ OPCODE(              "RRCA",  4),
	/* 0x10 */ OPCODE(              "STOP",  4),
	/* 0x11 */ OPCODE(          "LD DE,#h", 12),
	/* 0x12 */ OPCODE(         "LD (DE),A",  8),
	/* 0x13 */ OPCODE(            "INC DE",  8),
	/* 0x14 */ OPCODE(             "INC D",  4),
	/* 0x15 */ OPCODE(             "DEC D",  4),
	/* 0x16 */ OPCODE(           "LD D,*h",  8),
	/* 0x17 */ OPCODE(               "RLA",  4),
	/* 0x18 */ OPCODE(             "JR @h",  8),
	/* 0x19 */ OPCODE(         "ADD HL,DE",  8),
	/* 0x1A */ OPCODE(         "LD A,(DE)",  8),
	/* 0x1B */ OPCODE(            "DEC DE",  8),
	/* 0x1C */ OPCODE(             "INC E",  4),
	/* 0x1D */ OPCODE(             "DEC E",  4),
	/* 0x1E */ OPCODE(           "LD E,*h",  8),
	/* 0x1F */ OPCODE(               "RRA",  4),
	/* 0x20 */ OPCODE(          "JR NZ,@h",  8),
	/* 0x21 */ OPCODE(          "LD HL,#h", 12),
	/* 0x22 */ OPCODE(        "LD (HL+),A",  8),
	/* 0x23 */ OPCODE(            "INC HL",  8),
	/* 0x24 */ OPCODE(             "INC H",  4),
	/* 0x25 */ OPCODE(             "DEC H",  4),
	/* 0x26 */ OPCODE(           "LD H,*h",  8),
	/* 0x27 */ OPCODE(               "DAA",  4),
	/* 0x28 */ OPCODE(           "JR Z,@h",  8),
	/* 0x29 */ OPCODE(         "ADD HL,HL",  8),
	/* 0x2A */ OPCODE(        "LD A,(HL+)",  8),
	/* 0x2B */ OPCODE(            "DEC HL",  8),
	/* 0x2C */ OPCODE(             "INC L",  4),
	/* 0x2D */ OPCODE(             "DEC L",  4),
	/* 0x2E */ OPCODE(           "LD L,*h",  8),
	/* 0x2F */ OPCODE(               "CPL",  4),
	/* 0x30 */ OPCODE(          "JR NC,@h",  8),
	/* 0x31 */ OPCODE(          "LD SP,#h", 12),
	/* 0x32 */ OPCODE(        "LD (HL-),A",  8),
	/* 0x33 */ OPCODE(            "INC SP",  8),
	/* 0x34 */ OPCODE(          "INC (HL)", 12),
	/* 0x35 */ OPCODE(          "DEC (HL)", 12),
	/* 0x36 */ OPCODE(        "LD (HL),*h", 12),
	/* 0x37 */ OPCODE(               "SCF",  4),
	/* 0x38 */ OPCODE(           "JR C,@h",  8),
	/* 0x39 */ OPCODE(         "ADD HL,SP",  8),
	/* 0x3A */ OPCODE(        "LD A,(HL-)",  8),
	/* 0x3B */ OPCODE(            "DEC SP",  8),
	/* 0x3C */ OPCODE(             "INC A",  4),
	/* 0x3D */ OPCODE(             "DEC A",  4),
	/* 0x3E */ OPCODE(           "LD A,*h",  8),
	/* 0x3F */ OPCODE(               "CCF",  4),
	/* 0x40 */ OPCODE(            "LD B,B",  4),
	/* 0x41 */ OPCODE(            "LD B,C",  4),
	/* 0x42 */ OPCODE(            "LD B,D",  4),
	/* 0x43 */ OPCODE(            "LD B,E",  4),
	/* 0x44 */ OPCODE(            "LD B,H",  4),
	/* 0x45 */ OPCODE(            "LD B,L",  4),
	/* 0x46 */ OPCODE(         "LD B,(HL)",  8),
	/* 0x47 */ OPCODE(            "LD B,A",  4),
	/* 0x48 */ OPCODE(            "LD C,B",  4),
	/* 0x49 */ OPCODE(            "LD C,C",  4),
	/* 0x4A */ OPCODE(            "LD C,D",  4),
	/* 0x4B */ OPCODE(            "LD C,E",  4),
	/* 0x4C */ OPCODE(            "LD C,H",  4),
	/* 0x4D */ OPCODE(            "LD C,L",  4),
	/* 0x4E */ OPCODE(         "LD C,(HL)",  8),
	/* 0x4F */ OPCODE(            "LD C,A",  4),
	/* 0x50 */ OPCODE(            "LD D,B",  4),
	/* 0x51 */ OPCODE(            "LD D,C",  4),
	/* 0x52 */ OPCODE(            "LD D,D",  4),
	/* 0x53 */ OPCODE(            "LD D,E",  4),
	/* 0x54 */ OPCODE(            "LD D,H",  4),
	/* 0x55 */ OPCODE(            "LD D,L",  4),
	/* 0x56 */ OPCODE(         "LD D,(HL)",  8),
	/* 0x57 */ OPCODE(            "LD D,A",  4),
	/* 0x58 */ OPCODE(            "LD E,B",  4),
	/* 0x59 */ OPCODE(            "LD E,C",  4),
	/* 0x5A */ OPCODE(            "LD E,D",  4),
	/* 0x5B */ OPCODE(            "LD E,E",  4),
	/* 0x5C */ OPCODE(            "LD E,H",  4),
	/* 0x5D */ OPCODE(            "LD E,L",  4),
	/* 0x5E */ OPCODE(         "LD E,(HL)",  8),
	/* 0x5F */ OPCODE(            "LD E,A",  4),
	/* 0x60 */ OPCODE(            "LD H,B",  4),
	/* 0x61 */ OPCODE(            "LD H,C",  4),
	/* 0x62 */ OPCODE(            "LD H,D",  4),
	/* 0x63 */ OPCODE(            "LD H,E",  4),
	/* 0x64 */ OPCODE(            "LD H,H",  4),
	/* 0x65 */ OPCODE(            "LD H,L",  4),
	/* 0x66 */ OPCODE(         "LD H,(HL)",  8),
	/* 0x67 */ OPCODE(            "LD H,A",  4),
	/* 0x68 */ OPCODE(            "LD L,B",  4),
	/* 0x69 */ OPCODE(            "LD L,C",  4),
	/* 0x6A */ OPCODE(            "LD L,D",  4),
	/* 0x6B */ OPCODE(            "LD L,E",  4),
	/* 0x6C */ OPCODE(            "LD L,H",  4),
	/* 0x6D */ OPCODE(            "LD L,L",  4),
	/* 0x6E */ OPCODE(         "LD L,(HL)",  8),
	/* 0x6F */ OPCODE(            "LD L,A",  4),
	/* 0x70 */ OPCODE(         "LD (HL),B",  8),
	/* 0x71 */ OPCODE(         "LD (HL),C",  8),
	/* 0x72 */ OPCODE(         "LD (HL),D",  8),
	/* 0x73 */ OPCODE(         "LD (HL),E",  8),
	/* 0x74 */ OPCODE(         "LD (HL),H",  8),
	/* 0x75 */ OPCODE(         "LD (HL),L",  8),
	/* 0x76 */ OPCODE(              "HALT",  4),
	/* 0x77 */ OPCODE(         "LD (HL),A",  8),
	/* 0x78 */ OPCODE(            "LD A,B",  4),
	/* 0x79 */ OPCODE(            "LD A,C",  4),
	/* 0x7A */ OPCODE(            "LD A,D",  4),
	/* 0x7B */ OPCODE(            "LD A,E",  4),
	/* 0x7C */ OPCODE(            "LD A,H",  4),
	/* 0x7D */ OPCODE(            "LD A,L",  4),
	/* 0x7E */ OPCODE(         "LD A,(HL)",  8),
	/* 0x7F */ OPCODE(            "LD A,A",  4),
	/* 0x80 */ OPCODE(             "ADD B",  4),
	/* 0x81 */ OPCODE(             "ADD C",  4),
	/* 0x82 */ OPCODE(             "ADD D",  4),
	/* 0x83 */ OPCODE(             "ADD E",  4),
	/* 0x84 */ OPCODE(             "ADD H",  4),
	/* 0x85 */ OPCODE(             "ADD L",  4),
	/* 0x86 */ OPCODE(          "ADD (HL)",  8),
	/* 0x87 */ OPCODE(             "ADD A",  4),
	/* 0x88 */ OPCODE(             "ADC B",  4),
	/* 0x89 */ OPCODE(             "ADC C",  4),
	/* 0x8A */ OPCODE(             "ADC D",  4),
	/* 0x8B */ OPCODE(             "ADC E",  4),
	/* 0x8C */ OPCODE(             "ADC H",  4),
	/* 0x8D */ OPCODE(             "ADC L",  4),
	/* 0x8E */ OPCODE(          "ADC (HL)",  8),
	/* 0x8F */ OPCODE(             "ADC A",  4),
	/* 0x90 */ OPCODE(             "SUB B",  4),
	/* 0x91 */ OPCODE(             "SUB C",  4),
	/* 0x92 */ OPCODE(             "SUB D",  4),
	/* 0x93 */ OPCODE(             "SUB E",  4),
	/* 0x94 */ OPCODE(             "SUB H",  4),
	/* 0x95 */ OPCODE(             "SUB L",  4),
	/* 0x96 */ OPCODE(          "SUB (HL)",  8),
	/* 0x97 */ OPCODE(             "SUB A",  4),
	/* 0x98 */ OPCODE(             "SBC B",  4),
	/* 0x99 */ OPCODE(             "SBC C",  4),
	/* 0x9A */ OPCODE(             "SBC D",  4),
	/* 0x9B */ OPCODE(             "SBC E",  4),
	/* 0x9C */ OPCODE(             "SBC H",  4),
	/* 0x9D */ OPCODE(             "SBC L",  4),
	/* 0x9E */ OPCODE(          "SBC (HL)",  8),
	/* 0x9F */ OPCODE(             "SBC A",  4),
	/* 0xA0 */ OPCODE(             "AND B",  4),
	/* 0xA1 */ OPCODE(             "AND C",  4),
	/* 0xA2 */ OPCODE(             "AND D",  4),
	/* 0xA3 */ OPCODE(             "AND E",  4),
	/* 0xA4 */ OPCODE(             "AND H",  4),
	/* 0xA5 */ OPCODE(             "AND L",  4),
	/* 0xA6 */ OPCODE(          "AND (HL)",  8),
	/* 0xA7 */ OPCODE(             "AND A",  4),
	/* 0xA8 */ OPCODE(             "XOR B",  4),
	/* 0xA9 */ OPCODE(             "XOR C",  4),
	/* 0xAA */ OPCODE(             "XOR D",  4),
	/* 0xAB */ OPCODE(             "XOR E",  4),
	/* 0xAC */ OPCODE(             "XOR H",  4),
	/* 0xAD */ OPCODE(             "XOR L",  4),
	/* 0xAE */ OPCODE(          "XOR (HL)",  8),
	/* 0xAF */ OPCODE(             "XOR A",  4),
	/* 0xB0 */ OPCODE(              "OR B",  4),
	/* 0xB1 */ OPCODE(              "OR C",  4),
	/* 0xB2 */ OPCODE(              "OR D",  4),
	/* 0xB3 */ OPCODE(              "OR E",  4),
	/* 0xB4 */ OPCODE(              "OR H",  4),
	/* 0xB5 */ OPCODE(              "OR L",  4),
	/* 0xB6 */ OPCODE(           "OR (HL)",  8),
	/* 0xB7 */ OPCODE(              "OR A",  4),
	/* 0xB8 */ OPCODE(              "CP B",  4),
	/* 0xB9 */ OPCODE(              "CP C",  4),
	/* 0xBA */ OPCODE(              "CP D",  4),
	/* 0xBB */ OPCODE(              "CP E",  4),
	/* 0xBC */ OPCODE(              "CP H",  4),
	/* 0xBD */ OPCODE(              "CP L",  4),
	/* 0xBE */ OPCODE(           "CP (HL)",  8),
	/* 0xBF */ OPCODE(              "CP A",  4),
	/* 0xC0 */ OPCODE(            "RET NZ",  8),
	/* 0xC1 */ OPCODE(            "POP BC", 12),
	/* 0xC2 */ OPCODE(          "JP NZ,#h", 12),
	/* 0xC3 */ OPCODE(             "JP #h", 12),
	/* 0xC4 */ OPCODE(        "CALL NZ,#h", 12),
	/* 0xC5 */ OPCODE(           "PUSH BC", 16),
	/* 0xC6 */ OPCODE(            "ADD *h",  8),
	/* 0xC7 */ OPCODE(           "RST 00h", 32),
	/* 0xC8 */ OPCODE(             "RET Z",  8),
	/* 0xC9 */ OPCODE(               "RET",  8),
	/* 0xCA */ OPCODE(           "JP Z,#h", 12),
	/* 0xCB */ OPCODE(          "EXTENDED",  0),
	/* 0xCC */ OPCODE(         "CALL Z,#h", 12),
	/* 0xCD */ OPCODE(           "CALL #h", 12),
	/* 0xCE */ OPCODE(            "ADC *h",  8),
	/* 0xCF */ OPCODE(           "RST 08h", 32),
	/* 0xD0 */ OPCODE(            "RET NC",  8),
	/* 0xD1 */ OPCODE(            "POP DE", 12),
	/* 0xD2 */ OPCODE(          "JP NC,#h", 12),
	/* 0xD3 */ {0},
	/* 0xD4 */ OPCODE(        "CALL NC,#h", 12),
	/* 0xD5 */ OPCODE(           "PUSH DE", 16),
	/* 0xD6 */ OPCODE(            "SUB *h",  8),
	/* 0xD7 */ OPCODE(           "RST 10h", 32),
	/* 0xD8 */ OPCODE(             "RET C",  8),
	/* 0xD9 */ OPCODE(              "RETI",  8),
	/* 0xDA */ OPCODE(           "JP C,#h", 12),
	/* 0xDB */ {0},
	/* 0xDC */ OPCODE(         "CALL C,#h", 12),
	/* 0xDD */ {0},
	/* 0xDE */ OPCODE(            "SBC *h",  8),
	/* 0xDF */ OPCODE(           "RST 18h", 32),
	/* 0xE0 */ OPCODE(       "LD (FF*h),A", 12),
	/* 0xE1 */ OPCODE(            "POP HL", 12),
	/* 0xE2 */ OPCODE(    "LD (FF00h+C),A",  8),
	/* 0xE3 */ {0},
	/* 0xE4 */ {0},
	/* 0xE5 */ OPCODE(           "PUSH HL", 16),
	/* 0xE6 */ OPCODE(            "AND *h",  8),
	/* 0xE7 */ OPCODE(           "RST 20h", 32),
	/* 0xE8 */ OPCODE(         "ADD SP,@h", 16),
	/* 0xE9 */ OPCODE(          "LD PC,HL",  4),
	/* 0xEA */ OPCODE(         "LD (#h),A", 16),
	/* 0xEB */ {0},
	/* 0xEC */ {0},
	/* 0xED */ {0},
	/* 0xEE */ OPCODE(            "XOR *h",  8),
	/* 0xEF */ OPCODE(           "RST 28h", 32),
	/* 0xF0 */ OPCODE(       "LD A,(FF*h)", 12),
	/* 0xF1 */ OPCODE(            "POP AF", 12),
	/* 0xF2 */ OPCODE(    "LD A,(FF00h+C)",  8),
	/* 0xF3 */ OPCODE(                "DI",  4),
	/* 0xF4 */ {0},
	/* 0xF5 */ OPCODE(           "PUSH AF", 16),
	/* 0xF6 */ OPCODE(             "OR *h",  8),
	/* 0xF7 */ OPCODE(           "RST 30h", 32),
	/* 0xF8 */ OPCODE(        "LDHL SP,@h", 12),
	/* 0xF9 */ OPCODE(          "LD SP,HL",  8),
	/* 0xFA */ OPCODE(         "LD A,(#h)", 16),
	/* 0xFB */ OPCODE(                "EI",  4),
	/* 0xFC */ {0},
	/* 0xFD */ {0},
	/* 0xFE */ OPCODE(             "CP *h",  8),
	/* 0xFF */ OPCODE(           "RST 38h", 32),
};

opcode_meta_t const ext_opcode_meta[] = {
	/* 0x00 */ OPCODE(             "RLC B",  8),
	/* 0x01 */ OPCODE(             "RLC C",  8),
	/* 0x02 */ OPCODE(             "RLC D",  8),
	/* 0x03 */ OPCODE(             "RLC E",  8),
	/* 0x04 */ OPCODE(             "RLC H",  8),
	/* 0x05 */ OPCODE(             "RLC L",  8),
	/* 0x06 */ OPCODE(          "RLC (HL)", 16),
	/* 0x07 */ OPCODE(             "RLC A",  8),
	/* 0x08 */ OPCODE(             "RRC B",  8),
	/* 0x09 */ OPCODE(             "RRC C",  8),
	/* 0x0A */ OPCODE(             "RRC D",  8),
	/* 0x0B */ OPCODE(             "RRC E",  8),
	/* 0x0C */ OPCODE(             "RRC H",  8),
	/* 0x0D */ OPCODE(             "RRC L",  8),
	/* 0x0E */ OPCODE(          "RRC (HL)", 16),
	/* 0x0F */ OPCODE(             "RRC A",  8),
	/* 0x10 */ OPCODE(              "RL B",  8),
	/* 0x11 */ OPCODE(              "RL C",  8),
	/* 0x12 */ OPCODE(              "RL D",  8),
	/* 0x13 */ OPCODE(              "RL E",  8),
	/* 0x14 */ OPCODE(              "RL H",  8),
	/* 0x15 */ OPCODE(              "RL L",  8),
	/* 0x16 */ OPCODE(           "RL (HL)", 16),
	/* 0x17 */ OPCODE(              "RL A",  8),
	/* 0x18 */ OPCODE(              "RR B",  8),
	/* 0x19 */ OPCODE(              "RR C",  8),
	/* 0x1A */ OPCODE(              "RR D",  8),
	/* 0x1B */ OPCODE(              "RR E",  8),
	/* 0x1C */ OPCODE(              "RR H",  8),
	/* 0x1D */ OPCODE(              "RR L",  8),
	/* 0x1E */ OPCODE(           "RR (HL)", 16),
	/* 0x1F */ OPCODE(              "RR A",  8),
	/* 0x20 */ OPCODE(             "SLA B",  8),
	/* 0x21 */ OPCODE(             "SLA C",  8),
	/* 0x22 */ OPCODE(             "SLA D",  8),
	/* 0x23 */ OPCODE(             "SLA E",  8),
	/* 0x24 */ OPCODE(             "SLA H",  8),
	/* 0x25 */ OPCODE(             "SLA L",  8),
	/* 0x26 */ OPCODE(          "SLA (HL)", 16),
	/* 0x27 */ OPCODE(             "SLA A",  8),
	/* 0x28 */ OPCODE(             "SRA B",  8),
	/* 0x29 */ OPCODE(             "SRA C",  8),
	/* 0x2A */ OPCODE(             "SRA D",  8),
	/* 0x2B */ OPCODE(             "SRA E",  8),
	/* 0x2C */ OPCODE(             "SRA H",  8),
	/* 0x2D */ OPCODE(             "SRA L",  8),
	/* 0x2E */ OPCODE(          "SRA (HL)", 16),
	/* 0x2F */ OPCODE(             "SRA A",  8),
	/* 0x30 */ OPCODE(            "SWAP B",  8),
	/* 0x31 */ OPCODE(            "SWAP C",  8),
	/* 0x32 */ OPCODE(            "SWAP D",  8),
	/* 0x33 */ OPCODE(            "SWAP E",  8),
	/* 0x34 */ OPCODE(            "SWAP H",  8),
	/* 0x35 */ OPCODE(            "SWAP L",  8),
	/* 0x36 */ OPCODE(         "SWAP (HL)", 16),
	/* 0x37 */ OPCODE(            "SWAP A",  8),
	/* 0x38 */ OPCODE(             "SRL B",  8),
	/* 0x39 */ OPCODE(             "SRL C",  8),
	/* 0x3A */ OPCODE(             "SRL D",  8),
	/* 0x3B */ OPCODE(             "SRL E",  8),
	/* 0x3C */ OPCODE(             "SRL H",  8),
	/* 0x3D */ OPCODE(             "SRL L",  8),
	/* 0x3E */ OPCODE(          "SRL (HL)", 16),
	/* 0x3F */ OPCODE(             "SRL A",  8),
	/* 0x40 */ OPCODE(           "BIT 0,B",  8),
	/* 0x41 */ OPCODE(           "BIT 0,C",  8),
	/* 0x42 */ OPCODE(           "BIT 0,D",  8),
	/* 0x43 */ OPCODE(           "BIT 0,E",  8),
	/* 0x44 */ OPCODE(           "BIT 0,H",  8),
	/* 0x45 */ OPCODE(           "BIT 0,L",  8),
	/* 0x46 */ OPCODE(        "BIT 0,(HL)", 16),
	/* 0x47 */ OPCODE(           "BIT 0,A",  8),
	/* 0x48 */ OPCODE(           "BIT 1,B",  8),
	/* 0x49 */ OPCODE(           "BIT 1,C",  8),
	/* 0x4A */ OPCODE(           "BIT 1,D",  8),
	/* 0x4B */ OPCODE(           "BIT 1,E",  8),
	/* 0x4C */ OPCODE(           "BIT 1,H",  8),
	/* 0x4D */ OPCODE(           "BIT 1,L",  8),
	/* 0x4E */ OPCODE(        "BIT 1,(HL)", 16),
	/* 0x4F */ OPCODE(           "BIT 1,A",  8),
	/* 0x50 */ OPCODE(           "BIT 2,B",  8),
	/* 0x51 */ OPCODE(           "BIT 2,C",  8),
	/* 0x52 */ OPCODE(           "BIT 2,D",  8),
	/* 0x53 */ OPCODE(           "BIT 2,E",  8),
	/* 0x54 */ OPCODE(           "BIT 2,H",  8),
	/* 0x55 */ OPCODE(           "BIT 2,L",  8),
	/* 0x56 */ OPCODE(        "BIT 2,(HL)", 16),
	/* 0x57 */ OPCODE(           "BIT 2,A",  8),
	/* 0x58 */ OPCODE(           "BIT 3,B",  8),
	/* 0x59 */ OPCODE(           "BIT 3,C",  8),
	/* 0x5A */ OPCODE(           "BIT 3,D",  8),
	/* 0x5B */ OPCODE(           "BIT 3,E",  8),
	/* 0x5C */ OPCODE(           "BIT 3,H",  8),
	/* 0x5D */ OPCODE(           "BIT 3,L",  8),
	/* 0x5E */ OPCODE(        "BIT 3,(HL)", 16),
	/* 0x5F */ OPCODE(           "BIT 3,A",  8),
	/* 0x60 */ OPCODE(           "BIT 4,B",  8),
	/* 0x61 */ OPCODE(           "BIT 4,C",  8),
	/* 0x62 */ OPCODE(           "BIT 4,D",  8),
	/* 0x63 */ OPCODE(           "BIT 4,E",  8),
	/* 0x64 */ OPCODE(           "BIT 4,H",  8),
	/* 0x65 */ OPCODE(           "BIT 4,L",  8),
	/* 0x66 */ OPCODE(        "BIT 4,(HL)", 16),
	/* 0x67 */ OPCODE(           "BIT 4,A",  8),
	/* 0x68 */ OPCODE(           "BIT 5,B",  8),
	/* 0x69 */ OPCODE(           "BIT 5,C",  8),
	/* 0x6A */ OPCODE(           "BIT 5,D",  8),
	/* 0x6B */ OPCODE(           "BIT 5,E",  8),
	/* 0x6C */ OPCODE(           "BIT 5,H",  8),
	/* 0x6D */ OPCODE(           "BIT 5,L",  8),
	/* 0x6E */ OPCODE(        "BIT 5,(HL)", 16),
	/* 0x6F */ OPCODE(           "BIT 5,A",  8),
	/* 0x70 */ OPCODE(           "BIT 6,B",  8),
	/* 0x71 */ OPCODE(           "BIT 6,C",  8),
	/* 0x72 */ OPCODE(           "BIT 6,D",  8),
	/* 0x73 */ OPCODE(           "BIT 6,E",  8),
	/* 0x74 */ OPCODE(           "BIT 6,H",  8),
	/* 0x75 */ OPCODE(           "BIT 6,L",  8),
	/* 0x76 */ OPCODE(        "BIT 6,(HL)", 16),
	/* 0x77 */ OPCODE(           "BIT 6,A",  8),
	/* 0x78 */ OPCODE(           "BIT 7,B",  8),
	/* 0x79 */ OPCODE(           "BIT 7,C",  8),
	/* 0x7A */ OPCODE(           "BIT 7,D",  8),
	/* 0x7B */ OPCODE(           "BIT 7,E",  8),
	/* 0x7C */ OPCODE(           "BIT 7,H",  8),
	/* 0x7D */ OPCODE(           "BIT 7,L",  8),
	/* 0x7E */ OPCODE(        "BIT 7,(HL)", 16),
	/* 0x7F */ OPCODE(           "BIT 7,A",  8),
	/* 0x80 */ OPCODE(           "RES 0,B",  8),
	/* 0x81 */ OPCODE(           "RES 0,C",  8),
	/* 0x82 */ OPCODE(           "RES 0,D",  8),
	/* 0x83 */ OPCODE(           "RES 0,E",  8),
	/* 0x84 */ OPCODE(           "RES 0,H",  8),
	/* 0x85 */ OPCODE(           "RES 0,L",  8),
	/* 0x86 */ OPCODE(        "RES 0,(HL)", 16),
	/* 0x87 */ OPCODE(           "RES 0,A",  8),
	/* 0x88 */ OPCODE(           "RES 1,B",  8),
	/* 0x89 */ OPCODE(           "RES 1,C",  8),
	/* 0x8A */ OPCODE(           "RES 1,D",  8),
	/* 0x8B */ OPCODE(           "RES 1,E",  8),
	/* 0x8C */ OPCODE(           "RES 1,H",  8),
	/* 0x8D */ OPCODE(           "RES 1,L",  8),
	/* 0x8E */ OPCODE(        "RES 1,(HL)", 16),
	/* 0x8F */ OPCODE(           "RES 1,A",  8),
	/* 0x90 */ OPCODE(           "RES 2,B",  8),
	/* 0x91 */ OPCODE(           "RES 2,C",  8),
	/* 0x92 */ OPCODE(           "RES 2,D",  8),
	/* 0x93 */ OPCODE(           "RES 2,E",  8),
	/* 0x94 */ OPCODE(           "RES 2,H",  8),
	/* 0x95 */ OPCODE(           "RES 2,L",  8),
	/* 0x96 */ OPCODE(        "RES 2,(HL)", 16),
	/* 0x97 */ OPCODE(           "RES 2,A",  8),
	/* 0x98 */ OPCODE(           "RES 3,B",  8),
	/* 0x99 */ OPCODE(           "RES 3,C",  8),
	/* 0x9A */ OPCODE(           "RES 3,D",  8),
	/* 0x9B */ OPCODE(           "RES 3,E",  8),
	/* 0x9C */ OPCODE(           "RES 3,H",  8),
	/* 0x9D */ OPCODE(           "RES 3,L",  8),
	/* 0x9E */ OPCODE(        "RES 3,(HL)", 16),
	/* 0x9F */ OPCODE(           "RES 3,A",  8),
	/* 0xA0 */ OPCODE(           "RES 4,B",  8),
	/* 0xA1 */ OPCODE(           "RES 4,C",  8),
	/* 0xA2 */ OPCODE(           "RES 4,D",  8),
	/* 0xA3 */ OPCODE(           "RES 4,E",  8),
	/* 0xA4 */ OPCODE(           "RES 4,H",  8),
	/* 0xA5 */ OPCODE(           "RES 4,L",  8),
	/* 0xA6 */ OPCODE(        "RES 4,(HL)", 16),
	/* 0xA7 */ OPCODE(           "RES 4,A",  8),
	/* 0xA8 */ OPCODE(           "RES 5,B",  8),
	/* 0xA9 */ OPCODE(           "RES 5,C",  8),
	/* 0xAA */ OPCODE(           "RES 5,D",  8),
	/* 0xAB */ OPCODE(           "RES 5,E",  8),
	/* 0xAC */ OPCODE(           "RES 5,H",  8),
	/* 0xAD */ OPCODE(           "RES 5,L",  8),
	/* 0xAE */ OPCODE(        "RES 5,(HL)", 16),
	/* 0xAF */ OPCODE(           "RES 5,A",  8),
	/* 0xB0 */ OPCODE(           "RES 6,B",  8),
	/* 0xB1 */ OPCODE(           "RES 6,C",  8),
	/* 0xB2 */ OPCODE(           "RES 6,D",  8),
	/* 0xB3 */ OPCODE(           "RES 6,E",  8),
	/* 0xB4 */ OPCODE(           "RES 6,H",  8),
	/* 0xB5 */ OPCODE(           "RES 6,L",  8),
	/* 0xB6 */ OPCODE(        "RES 6,(HL)", 16),
	/* 0xB7 */ OPCODE(           "RES 6,A",  8),
	/* 0xB8 */ OPCODE(           "RES 7,B",  8),
	/* 0xB9 */ OPCODE(           "RES 7,C",  8),
	/* 0xBA */ OPCODE(           "RES 7,D",  8),
	/* 0xBB */ OPCODE(           "RES 7,E",  8),
	/* 0xBC */ OPCODE(           "RES 7,H",  8),
	/* 0xBD */ OPCODE(           "RES 7,L",  8),
	/* 0xBE */ OPCODE(        "RES 7,(HL)", 16),
	/* 0xBF */ OPCODE(           "RES 7,A",  8),
	/* 0xC0 */ OPCODE(           "SET 0,B",  8),
	/* 0xC1 */ OPCODE(           "SET 0,C",  8),
	/* 0xC2 */ OPCODE(           "SET 0,D",  8),
	/* 0xC3 */ OPCODE(           "SET 0,E",  8),
	/* 0xC4 */ OPCODE(           "SET 0,H",  8),
	/* 0xC5 */ OPCODE(           "SET 0,L",  8),
	/* 0xC6 */ OPCODE(        "SET 0,(HL)", 16),
	/* 0xC7 */ OPCODE(           "SET 0,A",  8),
	/* 0xC8 */ OPCODE(           "SET 1,B",  8),
	/* 0xC9 */ OPCODE(           "SET 1,C",  8),
	/* 0xCA */ OPCODE(           "SET 1,D",  8),
	/* 0xCB */ OPCODE(           "SET 1,E",  8),
	/* 0xCC */ OPCODE(           "SET 1,H",  8),
	/* 0xCD */ OPCODE(           "SET 1,L",  8),
	/* 0xCE */ OPCODE(        "SET 1,(HL)", 16),
	/* 0xCF */ OPCODE(           "SET 1,A",  8),
	/* 0xD0 */ OPCODE(           "SET 2,B",  8),
	/* 0xD1 */ OPCODE(           "SET 2,C",  8),
	/* 0xD2 */ OPCODE(           "SET 2,D",  8),
	/* 0xD3 */ OPCODE(           "SET 2,E",  8),
	/* 0xD4 */ OPCODE(           "SET 2,H",  8),
	/* 0xD5 */ OPCODE(           "SET 2,L",  8),
	/* 0xD6 */ OPCODE(        "SET 2,(HL)", 16),
	/* 0xD7 */ OPCODE(           "SET 2,A",  8),
	/* 0xD8 */ OPCODE(           "SET 3,B",  8),
	/* 0xD9 */ OPCODE(           "SET 3,C",  8),
	/* 0xDA */ OPCODE(           "SET 3,D",  8),
	/* 0xDB */ OPCODE(           "SET 3,E",  8),
	/* 0xDC */ OPCODE(           "SET 3,H",  8),
	/* 0xDD */ OPCODE(           "SET 3,L",  8),
	/* 0xDE */ OPCODE(        "SET 3,(HL)", 16),
	/* 0xDF */ OPCODE(           "SET 3,A",  8),
	/* 0xE0 */ OPCODE(           "SET 4,B",  8),
	/* 0xE1 */ OPCODE(           "SET 4,C",  8),
	/* 0xE2 */ OPCODE(           "SET 4,D",  8),
	/* 0xE3 */ OPCODE(           "SET 4,E",  8),
	/* 0xE4 */ OPCODE(           "SET 4,H",  8),
	/* 0xE5 */ OPCODE(           "SET 4,L",  8),
	/* 0xE6 */ OPCODE(        "SET 4,(HL)", 16),
	/* 0xE7 */ OPCODE(           "SET 4,A",  8),
	/* 0xE8 */ OPCODE(           "SET 5,B",  8),
	/* 0xE9 */ OPCODE(           "SET 5,C",  8),
	/* 0xEA */ OPCODE(           "SET 5,D",  8),
	/* 0xEB */ OPCODE(           "SET 5,E",  8),
	/* 0xEC */ OPCODE(           "SET 5,H",  8),
	/* 0xED */ OPCODE(           "SET 5,L",  8),
	/* 0xEE */ OPCODE(        "SET 5,(HL)", 16),
	/* 0xEF */ OPCODE(           "SET 5,A",  8),
	/* 0xF0 */ OPCODE(           "SET 6,B",  8),
	/* 0xF1 */ OPCODE(           "SET 6,C",  8),
	/* 0xF2 */ OPCODE(           "SET 6,D",  8),
	/* 0xF3 */ OPCODE(           "SET 6,E",  8),
	/* 0xF4 */ OPCODE(           "SET 6,H",  8),
	/* 0xF5 */ OPCODE(           "SET 6,L",  8),
	/* 0xF6 */ OPCODE(        "SET 6,(HL)", 16),
	/* 0xF7 */ OPCODE(           "SET 6,A",  8),
	/* 0xF8 */ OPCODE(           "SET 7,B",  8),
	/* 0xF9 */ OPCODE(           "SET 7,C",  8),
	/* 0xFA */ OPCODE(           "SET 7,D",  8),
	/* 0xFB */ OPCODE(           "SET 7,E",  8),
	/* 0xFC */ OPCODE(           "SET 7,H",  8),
	/* 0xFD */ OPCODE(           "SET 7,L",  8),
	/* 0xFE */ OPCODE(        "SET 7,(HL)", 16),
	/* 0xFF */ OPCODE(           "SET 7,A",  8),
};

#undef OPCODE
